### ISSUE TITLE
P8 hybrid watch

### ISSUE THREAD

**Issue by ildar** [StarGate01/p8b-infinitime#2]
I've P8 watch bought at mid-2020 (manufacturer's code MOY-TIN5). Tried both of your P8a and P8b FW.
1. with P8a FW: works fine except doesn't see Accel. About screen reports `Accel: ???`
2. with P8b FW: touch works for swype but NOT for taps. So I can't check if the Accel works. About screen reports I have `Accel: SC7A20, touch: b4.0.2`.

It seems I have a "chimera" P8 )))

BTW it's worth having the HW info stored somewhere, I like that site: https://smarterwat.ch/soc-list/nordic-semiconductor/p8.html . You can expand that or I can do that.
If you want, you can catch me in Matrix/Gitter.

**Comment by StarGate01** [comment]
Thank you for testing, I will add the profile in a few days when I return home.

How do you suggest calling this model? P8BG?

**Comment by ildar** [comment]
Fixed my post above.
I just found that:
1. my P8 HAS the LF osc;
2. my P8 fails to work with BLE using P8b FW

**Comment by StarGate01** [comment]
Please test the new 1.9.0.3 MOY-TIN5 release: https://github.com/StarGate01/p8b-infinitime/releases/tag/v1.9.0.3 .

**Comment by ildar** [comment]
Hi!
I'm sorry for disappearing. I finally installed the latest moy-tin5 FW and
it works great. Thanks.
I'll close this issue.

**Comment by ildar** [comment]
Unfortunately the latest 1.11.0 works only by 95%: BLE doesn't work. Scan
doesn't see the device.
Rolling back to 1.10.
Thanks a lot for your builds.

**Comment by StarGate01** [comment]
Thanks for your report. This is still for the MOY-TIN5?

**Comment by ildar** [comment]
yes, same watch.
