### ISSUE TITLE
Flashing infinitime onto storage via swd

### ISSUE THREAD

**Issue by 0x0000ff** [StarGate01/p8b-infinitime#4]
I can't seem to get it installed with the ota method. Can I flash mcuboot and Infinitime binaries onto the flash via SWD onto the storage?

Thanks,
0x0000ff

**Comment by StarGate01** [comment]
You can flash your watch via SWD, but you have to open it and connect a JLink or OpenOCD compatible adapter. See https://wiki.pine64.org/wiki/Reprogramming_the_PineTime for more info. Once you have opened the watch and connected to the SWD port, you can flash either the wasp-os bootloader.hex (and then follow the OTA instructions) or a compiled development version of InfiniTime. 

This leaves your watch unsealed against water etc, and you have to be very careful to not puncture the battery while opening the watch.

What are you having issues with concering the OTA method?

**Comment by 0x0000ff** [comment]
I'm stuck on the wasp-os bootloader. It doesn't seem to accept the images sent from NRFconnect on my phone. I think I'll go ahead with flashing with swd and see what happens.

**Comment by 0x0000ff** [comment]
I'm sorry, I never wrote it down before flashing. I opened it yesterday though and took a picture of what was printed on the motherboad. motherboard - if that helps. 
![IMG_20220626_213622](https://user-images.githubusercontent.com/1977210/175917814-9abca4ee-71e2-4178-adc8-855ae8ce9b65.jpg). My watch is at home now and i'm at work. I can get the IC serial numbers when I get back if that helps.

**Comment by StarGate01** [comment]
No worries. You can try to correlate the chips to https://github.com/StarGate01/p8b-infinitime/blob/master/HardwareVariants.md if you want to. Happy flashing!
