### ISSUE TITLE
Going back to different firmwares.

### ISSUE THREAD

**Issue by sanyi** [StarGate01/p8b-infinitime#5]
Hey there, cool project, tank you for the effort :)

I have a P8b watch, was able to install WaspOS, then this OS. Everything works only that I am not able to change to any different OS anymore. I am just asking to ensure i don't miss something obvious. 

I am using `ota-dfu-python/dfu.py` utilities from my linux machine.

Trying to load `python3 ota-dfu-python/dfu.py -z micropython.zip -a D4:EA:B6:CD:32:13 --legacy`  works but once done it just return to the 2 triangles infinitime screen.

Trying to load `python3 ota-dfu-python/dfu.py -z espruino_2v05.31_p8_SDK14_SD50.zip  -a D4:EA:B6:CD:32:13 --legacy` will fail after `Waiting for Image Size notification` with timeout.

Flashing back from this repository works again.

**Comment by StarGate01** [comment]
WaspOS and Infinitime use different memeory layouts, you can't just flash one over the other. Instead, you have to use a reloader - similar to the process you used to install Infinitime on the P8b in the first place. But this time, in the other direction. See https://wiki.pine64.org/wiki/Switching_your_PineTime_between_InfiniTime_and_Wasp-os § InfiniTime => Wasp-os , you need the file `build-pinetime/reloader-mcuboot.zip` from the WaspOS release. The reloading takes a bit and a few reboots, after which the watch should be able to accept a WaspOS image.

**Comment by sanyi** [comment]
Thank you :) I think i understand. Proceeded that way, my watch is now in a boot loop and refuses to react to long button press. This could be me trying different things without knowing exactly what i am doing. I guess we can close this. If i am able to fix it i will comment on the issue.

**Comment by StarGate01** [comment]
The button mapping is probably incorrect for the P8, leading to a nonfunctional button. You need to reboot the watch somehow, either by letting the battery drain overnight, or by disconnecting the battery shortly if you already opened the watch.

**Comment by sanyi** [comment]
Something went very wrong. Nor battery depletion helped. Ended up opening the watch, I will probably program it directly. Not a big deal since I was mainly exploring how to use this watch as a micro wall mounted HMI. Closing this issue since it is not relevant. Thank you.

**Comment by StarGate01** [comment]
Thanks for the feedback; I will test going back to waspOS for my next release and provide a modified reloader for the P8.
