### ISSUE TITLE
Flashing MOY-TON5 back

### ISSUE THREAD

**Issue by mrazuri** [StarGate01/p8b-infinitime#6]
I´m really sorry for bother you, but I need help returnig to my P8b (TON5) stock firmware. So far I´ve the bin firmware file and I was trying to build a dfu zip witn nrfutil without success

**Comment by StarGate01** [comment]
Hm. I never went that route, you can try asking on the ATC1441 Discord (https://discord.gg/mhzKPpcu) or on Matrix (https://matrix.to/#/#nRF51822-Arduino-Mbed-smart-watch_Lobby:gitter.im)

**Comment by mrazuri** [comment]
Thanks
